/**
 * POST /api/admin/super/seo-pages/refresh-content
 *
 * Rewrites content for thin auto_daily pages (wordCount < 400).
 * Uses the same buildSeoContent() that /k/[keyword] pages use —
 * 1200+ words, 5 FAQs, category-specific tips.
 *
 * Body: { limit?: number }  (default 500 pages per call)
 */
import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import SeoPage from '@/models/SeoPage';
import { getUserFromRequest } from '@/lib/auth';
import { isSuperAdminRole } from '@/lib/adminAuth';
import { buildSeoContent } from '@/lib/seoContentBuilder';
import { computeQualityScore } from '@/lib/qualityScorer';

export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  const user = await getUserFromRequest(request);
  if (!user || !isSuperAdminRole(user.role)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  const body = await request.json().catch(() => ({}));
  const limit = Math.min(Number(body.limit) || 500, 2000);

  await connectDB();

  // Find thin pages (generated by old cron with <400 words)
  const thinPages = await SeoPage.find({
    $or: [
      { wordCount: { $lt: 400 } },
      { wordCount: { $exists: false } },
    ],
    isIndexable: { $ne: true }, // don't touch already-promoted pages
  })
    .select('slug keyword category')
    .limit(limit)
    .lean();

  if (!thinPages.length) {
    return NextResponse.json({ success: true, updated: 0, message: 'No thin pages found' });
  }

  const ops: any[] = [];
  let updated = 0;

  for (const page of thinPages as any[]) {
    const kw = (page.keyword || page.slug.replace(/-/g, ' ')).trim();
    if (!kw) continue;

    try {
      const built = buildSeoContent(kw);
      const qualityScore = computeQualityScore({
        wordCount: built.wordCount,
        viralScore: 70,
        trendingRank: 0,
        views: 0,
        hashtagCount: built.hashtags.length,
        faqCount: built.faqs.length,
      });

      ops.push({
        updateOne: {
          filter: { slug: page.slug },
          update: {
            $set: {
              title: built.title,
              metaTitle: built.metaTitle,
              metaDescription: built.metaDescription,
              content: built.content,
              hashtags: built.hashtags,
              relatedKeywords: built.relatedKeywords,
              wordCount: built.wordCount,
              qualityScore,
              category: built.category,
            },
          },
        },
      });
      updated++;
    } catch {
      // skip this page
    }
  }

  if (ops.length) {
    await SeoPage.bulkWrite(ops, { ordered: false });
  }

  return NextResponse.json({
    success: true,
    scanned: thinPages.length,
    updated,
    message: `Upgraded ${updated} thin pages to 1200+ word content`,
    timestamp: new Date().toISOString(),
  });
}
